name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  pre_deploy_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run jest tests
        run: npm test
      - name: Report jest test success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: Success
          details: Jest successful
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Report jest test failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          description: Failed
          details: Jest failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: 'http://localhost:5000'
      - name: Report e2e test success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: Success
          details: Cypress successful
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Report e2e test failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          description: Failed
          details: Cypress failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


  deployment_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Report deployment success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: Success
          details: Deployment successful
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Report deployment failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          description: Deployment Failed
          details: Test failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  version_change:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    needs: [pre_deploy_pipeline, deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Report version update success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          description: Success
          details: Version change successful
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Report version update failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          description: Failed
          details: Version change failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  check_status:
    runs-on: ubuntu-20.04
    steps:
      - name: Check URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-cw-ci.fly.dev
          max-attempts: 5
          retry-delay: 5s